
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAP", targetNamespace = "http://example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerSOAP {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prix", targetNamespace = "http://example.com/", className = "mypackage.Prix")
    @ResponseWrapper(localName = "prixResponse", targetNamespace = "http://example.com/", className = "mypackage.PrixResponse")
    @Action(input = "http://example.com/ServerSOAP/prixRequest", output = "http://example.com/ServerSOAP/prixResponse")
    public int prix();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prixTotal", targetNamespace = "http://example.com/", className = "mypackage.PrixTotal")
    @ResponseWrapper(localName = "prixTotalResponse", targetNamespace = "http://example.com/", className = "mypackage.PrixTotalResponse")
    @Action(input = "http://example.com/ServerSOAP/prixTotalRequest", output = "http://example.com/ServerSOAP/prixTotalResponse")
    public int prixTotal();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "livraison", targetNamespace = "http://example.com/", className = "mypackage.Livraison")
    @ResponseWrapper(localName = "livraisonResponse", targetNamespace = "http://example.com/", className = "mypackage.LivraisonResponse")
    @Action(input = "http://example.com/ServerSOAP/livraisonRequest", output = "http://example.com/ServerSOAP/livraisonResponse")
    public int livraison();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://example.com/", className = "mypackage.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://example.com/", className = "mypackage.AdditionResponse")
    @Action(input = "http://example.com/ServerSOAP/additionRequest", output = "http://example.com/ServerSOAP/additionResponse")
    public int addition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
